name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Deploy to Heroku
      env:
        HEROKU_OAUTH_ID: ${{ secrets.HEROKU_OAUTH_ID }}
        HEROKU_OAUTH_SECRET: ${{ secrets.HEROKU_OAUTH_SECRET }}
      run: |
        curl -n -X POST https://api.heroku.com/oauth/authorizations \
        -d '{"description":"GitHub Actions Deploy","scope":["global"],"expires_in":2592000}' \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3" \
        -u ${{ secrets.HEROKU_OAUTH_ID }}:${{ secrets.HEROKU_OAUTH_SECRET }}
        git init
        heroku git:remote -a your-heroku-app-name
        git add .
        git commit -m "Deploy to Heroku"
        git push heroku main -f
